plugin_dir: ~/.config/nvim/pack/strand/start

plugins:
  - Git: Glench/Vim-Jinja2-Syntax
  - Git: arzg/vim-rust-syntax-ext
  - Git: cocopon/inspecthi.vim
  - Git: jiangmiao/auto-pairs
  - Git: junegunn/fzf.vim
  - Git: junegunn/vim-easy-align
  - Git: lifepillar/vim-colortemplate
  - Git: lifepillar/vim-mucomplete
  - Git: romainl/Apprentice
  - Git: romainl/vim-cool
  - Git: rust-lang/rust.vim
  - Git: sgur/vim-editorconfig
  - Git: tpope/vim-commentary
  - Git: tpope/vim-endwise
  - Git: tpope/vim-fugitive
  - Git: tpope/vim-surround
  - Git: tpope/vim-unimpaired
  - Git: wellle/targets.vim
